# Generated by Django 6.0.4 on 2026-04-22 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=400)),
                ('batch_year', models.PositiveIntegerField()),
                ('team_members', models.TextField(help_text='Comma-separated list of team members')),
                ('project_description', models.TextField(blank=True)),
                ('report_pdf', models.URLField(blank=True, max_length=1000)),
                ('presentation_slides', models.URLField(blank=True, max_length=1000)),
                ('demo_video', models.URLField(blank=True, max_length=1000)),
                ('gallery_images', models.TextField(blank=True, help_text='Comma-separated image URLs')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived')], default='ongoing', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_capstones', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-batch_year', 'project_title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🔬', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['research_area'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('authors', models.CharField(max_length=400)),
                ('abstract', models.TextField(blank=True)),
                ('publication_year', models.PositiveIntegerField()),
                ('pdf_link', models.URLField(blank=True, max_length=1000)),
                ('citations', models.PositiveIntegerField(default=0)),
                ('dataset_link', models.URLField(blank=True, max_length=1000)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('research_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='projects.researcharea')),
            ],
            options={
                'ordering': ['-publication_year', '-citations'],
            },
        ),
    ]
