# Generated by Django 5.2.5 on 2026-05-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capstone',
            options={'ordering': ['-passing_year', 'title']},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-passing_year', '-citations']},
        ),
        migrations.RenameField(
            model_name='capstone',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='capstone',
            old_name='report_pdf',
            new_name='pdf_link',
        ),
        migrations.RenameField(
            model_name='capstone',
            old_name='project_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='abstract',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='capstone',
            name='batch_year',
        ),
        migrations.RemoveField(
            model_name='capstone',
            name='faculty_supervisor',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='capstone',
            name='faculty_name',
            field=models.CharField(blank=True, help_text='Name of faculty supervisor', max_length=200),
        ),
        migrations.AddField(
            model_name='capstone',
            name='field',
            field=models.CharField(blank=True, help_text='Project category/field', max_length=200),
        ),
        migrations.AddField(
            model_name='capstone',
            name='passing_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='capstone',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='research/capstones/'),
        ),
        migrations.AddField(
            model_name='capstone',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='faculty_name',
            field=models.CharField(blank=True, help_text='Name of faculty supervisor/advisor', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='field',
            field=models.CharField(blank=True, help_text='Specific field of research', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='passing_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='research/papers/'),
        ),
        migrations.AddField(
            model_name='paper',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='research_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='projects.researcharea'),
        ),
    ]
