# Generated by Django 5.2.5 on 2026-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for verification', max_length=20),
        ),
    ]
