# Generated by Django 6.0.4 on 2026-04-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='semester',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/attachments/')),
                ('link_url', models.URLField(blank=True, max_length=1000)),
                ('is_link', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, help_text='Display name for the file or link', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.material')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
