# Generated by Django 6.0.4 on 2026-04-22 21:19

from django.db import migrations

def migrate_to_attachments(apps, schema_editor):
    Material = apps.get_model('materials', 'Material')
    MaterialAttachment = apps.get_model('materials', 'MaterialAttachment')

    for m in Material.objects.all():
        if getattr(m, 'file', None):
            MaterialAttachment.objects.create(
                material=m,
                file=m.file,
                is_link=False,
                name=m.file.name.split('/')[-1] if m.file.name else 'File'
            )
        if getattr(m, 'url', None):
            MaterialAttachment.objects.create(
                material=m,
                link_url=m.url,
                is_link=True,
                name='External Link'
            )

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_semester_material_year_materialattachment'),
    ]

    operations = [
        migrations.RunPython(migrate_to_attachments, reverse_migration),
    ]

