# Generated by Django 6.0.4 on 2026-04-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_migrate_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='url',
        ),
    ]
