# Generated by Django 5.2.5 on 2026-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_material_file_remove_material_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.CharField(blank=True, help_text='e.g. 3+1=4', max_length=20, null=True),
        ),
    ]
